/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sostratpmsinterface;

import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ffelez
 */
public class MainSostratPMSInterfaceFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainSostratPMSInterfaceFrame
     */
    public MainSostratPMSInterfaceFrame() {
        initComponents();
        
        fillLocations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfYear = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfEndPort = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfInitPort = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfShip = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfYear1 = new javax.swing.JTextField();
        tfETD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfNumber1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfETA = new javax.swing.JTextField();
        cbLocation = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        tfShip1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("New Visit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel1.add(jButton1, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Visit Year");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(jLabel1, gridBagConstraints);

        tfYear.setText("2014");
        tfYear.setPreferredSize(new java.awt.Dimension(100, 20));
        tfYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfYearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(tfYear, gridBagConstraints);

        jLabel2.setText("Initial Port");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(jLabel2, gridBagConstraints);

        tfEndPort.setText("21");
        tfEndPort.setPreferredSize(new java.awt.Dimension(100, 20));
        tfEndPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEndPortActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(tfEndPort, gridBagConstraints);

        jLabel3.setText("Visit Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(jLabel3, gridBagConstraints);

        tfNumber.setText("00000");
        tfNumber.setPreferredSize(new java.awt.Dimension(100, 20));
        tfNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumberActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(tfNumber, gridBagConstraints);

        jLabel4.setText("End Port");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(jLabel4, gridBagConstraints);

        tfInitPort.setText("20");
        tfInitPort.setPreferredSize(new java.awt.Dimension(100, 20));
        tfInitPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInitPortActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(tfInitPort, gridBagConstraints);

        jLabel5.setText("Ship Id");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(jLabel5, gridBagConstraints);

        tfShip.setText("1234");
        tfShip.setPreferredSize(new java.awt.Dimension(100, 20));
        tfShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfShipActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(tfShip, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jPanel3, gridBagConstraints);

        jTabbedPane1.addTab("New Visit", jPanel1);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel6.setText("Visit Year");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(jLabel6, gridBagConstraints);

        tfYear1.setText("2014");
        tfYear1.setPreferredSize(new java.awt.Dimension(100, 20));
        tfYear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfYear1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(tfYear1, gridBagConstraints);

        tfETD.setText("2014-02-12T17:50:00+02:00");
        tfETD.setPreferredSize(new java.awt.Dimension(170, 20));
        tfETD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfETDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(tfETD, gridBagConstraints);

        jLabel8.setText("Visit Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(jLabel8, gridBagConstraints);

        tfNumber1.setText("00000");
        tfNumber1.setPreferredSize(new java.awt.Dimension(100, 20));
        tfNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumber1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(tfNumber1, gridBagConstraints);

        jLabel9.setText("ETD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Location");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(jLabel10, gridBagConstraints);

        jLabel11.setText("ETA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(jLabel11, gridBagConstraints);

        tfETA.setText("2014-02-10T10:32:00+02:00");
        tfETA.setPreferredSize(new java.awt.Dimension(170, 20));
        tfETA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfETAActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(tfETA, gridBagConstraints);

        cbLocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(cbLocation, gridBagConstraints);

        jLabel7.setText("Ship Id");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(jLabel7, gridBagConstraints);

        tfShip1.setText("1234");
        tfShip1.setPreferredSize(new java.awt.Dimension(100, 20));
        tfShip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfShip1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(tfShip1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 494;
        gridBagConstraints.ipady = 207;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 0, 10);
        jPanel4.add(jPanel5, gridBagConstraints);

        jButton4.setText("New Stop");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 524, 15, 0);
        jPanel4.add(jButton4, gridBagConstraints);

        jTabbedPane1.addTab("New Stop", jPanel4);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Code", "Length", "Max Length"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 429;
        gridBagConstraints.ipady = 400;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jButton3, gridBagConstraints);

        jTabbedPane1.addTab("Locations", jPanel2);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        VisitInformation visitInformation = new VisitInformation();
        
        visitInformation.visitYear = tfYear.getText();
        visitInformation.visitNumber = tfNumber.getText();
        visitInformation.initialPort = tfInitPort.getText();
        visitInformation.endPort = tfEndPort.getText();
        visitInformation.shipId = tfShip.getText();
        
        Utils.SendVisitData(visitInformation);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfYearActionPerformed

    private void tfEndPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEndPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEndPortActionPerformed

    private void tfNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumberActionPerformed

    private void tfInitPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInitPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInitPortActionPerformed

    private void tfShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfShipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfShipActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        int i;
        for (i = 0; i < jTable1.getRowCount(); i++)
        {
            Utils.SendLocationData( (new LocationInformation ((String) jTable1.getValueAt(i, 0), 
                                                    (String) jTable1.getValueAt(i, 1),
                                                    (String) jTable1.getValueAt(i, 2),
                                                    (String) jTable1.getValueAt(i, 3),
                                                    (String) jTable1.getValueAt(i, 4))));
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfYear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfYear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfYear1ActionPerformed

    private void tfETDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfETDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfETDActionPerformed

    private void tfNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumber1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        StopInformation stopInformation = new StopInformation();
        
        stopInformation.visitYear = tfYear1.getText();
        stopInformation.visitNumber = tfNumber1.getText();
        stopInformation.location = findLocationId ((String) cbLocation.getSelectedItem());
        stopInformation.eta = tfETA.getText();
        stopInformation.etd = tfETD.getText();
        
        
        
        Utils.SendStopData(stopInformation);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tfETAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfETAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfETAActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        
        cbLocation.removeAllItems();
        int i;
        for (i = 0; i < jTable1.getRowCount(); i++)
        {
            String locationName = (String) jTable1.getValueAt(i, 1);
            cbLocation.addItem (locationName);
        }
        
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void tfShip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfShip1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfShip1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbLocation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfETA;
    private javax.swing.JTextField tfETD;
    private javax.swing.JTextField tfEndPort;
    private javax.swing.JTextField tfInitPort;
    private javax.swing.JTextField tfNumber;
    private javax.swing.JTextField tfNumber1;
    private javax.swing.JTextField tfShip;
    private javax.swing.JTextField tfShip1;
    private javax.swing.JTextField tfYear;
    private javax.swing.JTextField tfYear1;
    // End of variables declaration//GEN-END:variables

    private void fillLocations() {
        
        LinkedList<LocationInformation> locations = new LinkedList<>();
        
        locations.add(new LocationInformation ("1001", "name1", "ZZ1", "250", "100"));
        locations.add(new LocationInformation ("1002", "name2", "ZZ2", "450", "100"));
        locations.add(new LocationInformation ("1003", "name3", "ZZ3", "550", "300"));
        locations.add(new LocationInformation ("1004", "name4", "ZZ4", "650", "300"));
        locations.add(new LocationInformation ("1005", "name5", "ZZ5", "750", "200"));
        locations.add(new LocationInformation ("1006", "name6", "ZZ6", "850", "200"));
        
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        if (tableModel != null)
        {
            tableModel.setNumRows(locations.size());
            
            int position = 0;
            for (LocationInformation location : locations)
            {
                tableModel.setValueAt(location.id, position, 0);
                tableModel.setValueAt(location.name, position, 1);
                tableModel.setValueAt(location.code, position, 2);
                tableModel.setValueAt(location.length, position, 3);
                tableModel.setValueAt(location.maxLength, position, 4);
                
                position++;
            }
        }
    }

    private String findLocationId(String locationName) 
    {
        String result = "";

        int i;
        for (i = 0; i < jTable1.getRowCount(); i++)
        {
            if (locationName.equals ((String) jTable1.getValueAt(i, 1)))
            {
                result = (String) jTable1.getValueAt(i, 0);
            }
        }
        
        return result;        
    }
}
